{
    "url": "https://api.github.com/repos/NVIDIA/spark-rapids/issues/10566",
    "repository_url": "https://api.github.com/repos/NVIDIA/spark-rapids",
    "labels_url": "https://api.github.com/repos/NVIDIA/spark-rapids/issues/10566/labels{/name}",
    "comments_url": "https://api.github.com/repos/NVIDIA/spark-rapids/issues/10566/comments",
    "events_url": "https://api.github.com/repos/NVIDIA/spark-rapids/issues/10566/events",
    "html_url": "https://github.com/NVIDIA/spark-rapids/issues/10566",
    "id": 2175592679,
    "node_id": "I_kwDOD7z77c6BrOjn",
    "number": 10566,
    "title": "[BUG] Can't access Unity Catalogue data on Databricks AWS cluster ",
    "user": {
        "login": "captify-sivakhno",
        "id": 108534488,
        "node_id": "U_kgDOBnga2A",
        "avatar_url": "https://avatars.githubusercontent.com/u/108534488?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/captify-sivakhno",
        "html_url": "https://github.com/captify-sivakhno",
        "followers_url": "https://api.github.com/users/captify-sivakhno/followers",
        "following_url": "https://api.github.com/users/captify-sivakhno/following{/other_user}",
        "gists_url": "https://api.github.com/users/captify-sivakhno/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/captify-sivakhno/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/captify-sivakhno/subscriptions",
        "organizations_url": "https://api.github.com/users/captify-sivakhno/orgs",
        "repos_url": "https://api.github.com/users/captify-sivakhno/repos",
        "events_url": "https://api.github.com/users/captify-sivakhno/events{/privacy}",
        "received_events_url": "https://api.github.com/users/captify-sivakhno/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [
        {
            "id": 2061735874,
            "node_id": "MDU6TGFiZWwyMDYxNzM1ODc0",
            "url": "https://api.github.com/repos/NVIDIA/spark-rapids/labels/bug",
            "name": "bug",
            "color": "d73a4a",
            "default": true,
            "description": "Something isn't working"
        }
    ],
    "state": "open",
    "locked": false,
    "assignee": {
        "login": "SurajAralihalli",
        "id": 24796335,
        "node_id": "MDQ6VXNlcjI0Nzk2MzM1",
        "avatar_url": "https://avatars.githubusercontent.com/u/24796335?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/SurajAralihalli",
        "html_url": "https://github.com/SurajAralihalli",
        "followers_url": "https://api.github.com/users/SurajAralihalli/followers",
        "following_url": "https://api.github.com/users/SurajAralihalli/following{/other_user}",
        "gists_url": "https://api.github.com/users/SurajAralihalli/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/SurajAralihalli/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/SurajAralihalli/subscriptions",
        "organizations_url": "https://api.github.com/users/SurajAralihalli/orgs",
        "repos_url": "https://api.github.com/users/SurajAralihalli/repos",
        "events_url": "https://api.github.com/users/SurajAralihalli/events{/privacy}",
        "received_events_url": "https://api.github.com/users/SurajAralihalli/received_events",
        "type": "User",
        "site_admin": false
    },
    "assignees": [
        {
            "login": "SurajAralihalli",
            "id": 24796335,
            "node_id": "MDQ6VXNlcjI0Nzk2MzM1",
            "avatar_url": "https://avatars.githubusercontent.com/u/24796335?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/SurajAralihalli",
            "html_url": "https://github.com/SurajAralihalli",
            "followers_url": "https://api.github.com/users/SurajAralihalli/followers",
            "following_url": "https://api.github.com/users/SurajAralihalli/following{/other_user}",
            "gists_url": "https://api.github.com/users/SurajAralihalli/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/SurajAralihalli/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/SurajAralihalli/subscriptions",
            "organizations_url": "https://api.github.com/users/SurajAralihalli/orgs",
            "repos_url": "https://api.github.com/users/SurajAralihalli/repos",
            "events_url": "https://api.github.com/users/SurajAralihalli/events{/privacy}",
            "received_events_url": "https://api.github.com/users/SurajAralihalli/received_events",
            "type": "User",
            "site_admin": false
        }
    ],
    "milestone": null,
    "comments": 3,
    "created_at": "2024-03-08T09:03:52Z",
    "updated_at": "2024-03-13T20:20:29Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "body": "**Describe the bug**\r\nI have set up RAPIDS on Databricks AWS cluster (runtime 12.2.x-gpu-ml-scala2.12) as described in https://docs.nvidia.com/spark-rapids/user-guide/23.12.2/getting-started/databricks.html \r\nI then trying to read delta lake on the Unity Catalogue (we have it enabled as it's Databricks main data catalogue offering)\r\n\r\n`data = spark.read.format(\"delta\").table(\"table name\").toPandad()\r\n`\r\nand get access denied error:\r\n\r\n`: org.apache.spark.SparkException: Exception thrown in awaitResult: Job aborted due to stage failure: Task 0 in stage 5.0 failed 4 times, most recent failure: Lost task 0.3 in stage 5.0 (TID 4264) (172.17.190.255 executor 2): java.nio.file.AccessDeniedException: s3://categories/8i/part-00073-d55722a3-743e-4b23-93eb-d264d9f0b897.c000.snappy.parquet: getFileStatus on s3://categories/8i/part-00073-d55722a3-743e-4b23-93eb-d264d9f0b897.c000.snappy.parquet: com.amazonaws.services.s3.model.AmazonS3Exception: Forbidden`\r\n\r\n**Steps/Code to reproduce bug**\r\n[Please provide a list of steps or a code sample to reproduce the issue.\r\nAvoid posting private or sensitive data.]\r\n\r\nSet RAPIDS on 12.2.x-gpu-ml-scala2.12 Databricks AWS cluster runtime using \r\n\r\nspark.rapids.sql.concurrentGpuTasks 2\r\nspark.executorEnv.PYTHONPATH /databricks/jars/rapids-4-spark_2.12-23.12.2.jar:/databricks/spark/python\r\nspark.rapids.sql.python.gpu.enabled true\r\nspark.rapids.memory.pinnedPool.size 2G\r\nspark.rapids.sql.format.parquet.reader.type PERFILE\r\nspark.task.resource.gpu.amount 0.1\r\nspark.plugins com.nvidia.spark.SQLPlugin\r\nspark.python.daemon.module rapids.daemon_databricks\r\n\r\npip install cudf-cu11==23.12.1\r\n\r\nread any delta lake table on unity catalogue \r\n\r\n**Expected behavior**\r\nAs Unity Catalogue is Databricks main data catalogue offering and enabled by default, I would expect RAPIDS support unity data access. Without RAPIDS config cluster can access Unity Catalogue normally.\r\n\r\n**Additional context**\r\nAdd any other context about the problem here.\r\n",
    "closed_by": null,
    "reactions": {
        "url": "https://api.github.com/repos/NVIDIA/spark-rapids/issues/10566/reactions",
        "total_count": 0,
        "+1": 0,
        "-1": 0,
        "laugh": 0,
        "hooray": 0,
        "confused": 0,
        "heart": 0,
        "rocket": 0,
        "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/NVIDIA/spark-rapids/issues/10566/timeline",
    "performed_via_github_app": null,
    "state_reason": null
}