[
    {
        "url": "https://api.github.com/repos/NVIDIA/spark-rapids/issues/comments/1786343243",
        "html_url": "https://github.com/NVIDIA/spark-rapids/issues/9582#issuecomment-1786343243",
        "issue_url": "https://api.github.com/repos/NVIDIA/spark-rapids/issues/9582",
        "id": 1786343243,
        "node_id": "IC_kwDOD7z77c5qeW9L",
        "user": {
            "login": "pxLi",
            "id": 8086184,
            "node_id": "MDQ6VXNlcjgwODYxODQ=",
            "avatar_url": "https://avatars.githubusercontent.com/u/8086184?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/pxLi",
            "html_url": "https://github.com/pxLi",
            "followers_url": "https://api.github.com/users/pxLi/followers",
            "following_url": "https://api.github.com/users/pxLi/following{/other_user}",
            "gists_url": "https://api.github.com/users/pxLi/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/pxLi/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/pxLi/subscriptions",
            "organizations_url": "https://api.github.com/users/pxLi/orgs",
            "repos_url": "https://api.github.com/users/pxLi/repos",
            "events_url": "https://api.github.com/users/pxLi/events{/privacy}",
            "received_events_url": "https://api.github.com/users/pxLi/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2023-10-31T02:35:02Z",
        "updated_at": "2023-10-31T02:35:02Z",
        "author_association": "COLLABORATOR",
        "body": "should be fixed directly in the #9576 ",
        "reactions": {
            "url": "https://api.github.com/repos/NVIDIA/spark-rapids/issues/comments/1786343243/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/NVIDIA/spark-rapids/issues/comments/1787213413",
        "html_url": "https://github.com/NVIDIA/spark-rapids/issues/9582#issuecomment-1787213413",
        "issue_url": "https://api.github.com/repos/NVIDIA/spark-rapids/issues/9582",
        "id": 1787213413,
        "node_id": "IC_kwDOD7z77c5qhrZl",
        "user": {
            "login": "revans2",
            "id": 3441321,
            "node_id": "MDQ6VXNlcjM0NDEzMjE=",
            "avatar_url": "https://avatars.githubusercontent.com/u/3441321?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/revans2",
            "html_url": "https://github.com/revans2",
            "followers_url": "https://api.github.com/users/revans2/followers",
            "following_url": "https://api.github.com/users/revans2/following{/other_user}",
            "gists_url": "https://api.github.com/users/revans2/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/revans2/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/revans2/subscriptions",
            "organizations_url": "https://api.github.com/users/revans2/orgs",
            "repos_url": "https://api.github.com/users/revans2/repos",
            "events_url": "https://api.github.com/users/revans2/events{/privacy}",
            "received_events_url": "https://api.github.com/users/revans2/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2023-10-31T13:24:32Z",
        "updated_at": "2023-10-31T13:24:32Z",
        "author_association": "COLLABORATOR",
        "body": "@pxLi how does #9576, which is a build issue that in practice should not cause any runtime problems, just build problems is the cause of a core dump from sort? I just want to be sure that this was not closed on accident because this is a very serious and scary issue.",
        "reactions": {
            "url": "https://api.github.com/repos/NVIDIA/spark-rapids/issues/comments/1787213413/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/NVIDIA/spark-rapids/issues/comments/1787247914",
        "html_url": "https://github.com/NVIDIA/spark-rapids/issues/9582#issuecomment-1787247914",
        "issue_url": "https://api.github.com/repos/NVIDIA/spark-rapids/issues/9582",
        "id": 1787247914,
        "node_id": "IC_kwDOD7z77c5qhz0q",
        "user": {
            "login": "revans2",
            "id": 3441321,
            "node_id": "MDQ6VXNlcjM0NDEzMjE=",
            "avatar_url": "https://avatars.githubusercontent.com/u/3441321?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/revans2",
            "html_url": "https://github.com/revans2",
            "followers_url": "https://api.github.com/users/revans2/followers",
            "following_url": "https://api.github.com/users/revans2/following{/other_user}",
            "gists_url": "https://api.github.com/users/revans2/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/revans2/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/revans2/subscriptions",
            "organizations_url": "https://api.github.com/users/revans2/orgs",
            "repos_url": "https://api.github.com/users/revans2/repos",
            "events_url": "https://api.github.com/users/revans2/events{/privacy}",
            "received_events_url": "https://api.github.com/users/revans2/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2023-10-31T13:43:31Z",
        "updated_at": "2023-10-31T13:43:31Z",
        "author_association": "COLLABORATOR",
        "body": "From the stack trace it looks like the test failed, and then the bad access happens as we try to close the catalog.\r\n\r\nhttps://github.com/NVIDIA/spark-rapids/blob/d1573060301b70d187147697e3202fc26c8a8097/tests/src/test/scala/com/nvidia/spark/rapids/RmmSparkRetrySuiteBase.scala#L58\r\n\r\nThe test failed because of \r\n\r\nhttps://github.com/NVIDIA/spark-rapids/blob/d1573060301b70d187147697e3202fc26c8a8097/sql-plugin/src/main/scala/com/nvidia/spark/rapids/SortUtils.scala#L248\r\n\r\nWhich is something that we should look into, but I am much more concerned about the segfault that happened.  The secondary code appears to be a SEGV_ACCERR, which means we tried to access something that we don't have permission to access. My guess is that it is a use after free, but I am not 100% sure. It could also be that RMM had shut down already before we tried to clean up the memory.",
        "reactions": {
            "url": "https://api.github.com/repos/NVIDIA/spark-rapids/issues/comments/1787247914/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/NVIDIA/spark-rapids/issues/comments/1788023880",
        "html_url": "https://github.com/NVIDIA/spark-rapids/issues/9582#issuecomment-1788023880",
        "issue_url": "https://api.github.com/repos/NVIDIA/spark-rapids/issues/9582",
        "id": 1788023880,
        "node_id": "IC_kwDOD7z77c5qkxRI",
        "user": {
            "login": "revans2",
            "id": 3441321,
            "node_id": "MDQ6VXNlcjM0NDEzMjE=",
            "avatar_url": "https://avatars.githubusercontent.com/u/3441321?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/revans2",
            "html_url": "https://github.com/revans2",
            "followers_url": "https://api.github.com/users/revans2/followers",
            "following_url": "https://api.github.com/users/revans2/following{/other_user}",
            "gists_url": "https://api.github.com/users/revans2/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/revans2/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/revans2/subscriptions",
            "organizations_url": "https://api.github.com/users/revans2/orgs",
            "repos_url": "https://api.github.com/users/revans2/repos",
            "events_url": "https://api.github.com/users/revans2/events{/privacy}",
            "received_events_url": "https://api.github.com/users/revans2/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2023-10-31T20:56:30Z",
        "updated_at": "2023-10-31T20:56:46Z",
        "author_association": "COLLABORATOR",
        "body": "https://github.com/NVIDIA/spark-rapids/commit/9f12c272259e2c3c355e95ece980535f020bd93a is the patch that fixed the failure to happen, so I am hopeful that I can understand where the segfault came from. One of the scary things is that this got past our assertions and still got the segfault.",
        "reactions": {
            "url": "https://api.github.com/repos/NVIDIA/spark-rapids/issues/comments/1788023880/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/NVIDIA/spark-rapids/issues/comments/1788279587",
        "html_url": "https://github.com/NVIDIA/spark-rapids/issues/9582#issuecomment-1788279587",
        "issue_url": "https://api.github.com/repos/NVIDIA/spark-rapids/issues/9582",
        "id": 1788279587,
        "node_id": "IC_kwDOD7z77c5qlvsj",
        "user": {
            "login": "pxLi",
            "id": 8086184,
            "node_id": "MDQ6VXNlcjgwODYxODQ=",
            "avatar_url": "https://avatars.githubusercontent.com/u/8086184?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/pxLi",
            "html_url": "https://github.com/pxLi",
            "followers_url": "https://api.github.com/users/pxLi/followers",
            "following_url": "https://api.github.com/users/pxLi/following{/other_user}",
            "gists_url": "https://api.github.com/users/pxLi/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/pxLi/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/pxLi/subscriptions",
            "organizations_url": "https://api.github.com/users/pxLi/orgs",
            "repos_url": "https://api.github.com/users/pxLi/repos",
            "events_url": "https://api.github.com/users/pxLi/events{/privacy}",
            "received_events_url": "https://api.github.com/users/pxLi/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2023-11-01T01:56:37Z",
        "updated_at": "2023-11-01T01:56:37Z",
        "author_association": "COLLABORATOR",
        "body": "> @pxLi how does #9576, which is a build issue that in practice should not cause any runtime problems, just build problems is the cause of a core dump from sort? I just want to be sure that this was not closed on accident because this is a very serious and scary issue.\r\n\r\nI was told the issue was caused by the change, cc @NVnavkumar could share more",
        "reactions": {
            "url": "https://api.github.com/repos/NVIDIA/spark-rapids/issues/comments/1788279587/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/NVIDIA/spark-rapids/issues/comments/1788428391",
        "html_url": "https://github.com/NVIDIA/spark-rapids/issues/9582#issuecomment-1788428391",
        "issue_url": "https://api.github.com/repos/NVIDIA/spark-rapids/issues/9582",
        "id": 1788428391,
        "node_id": "IC_kwDOD7z77c5qmUBn",
        "user": {
            "login": "pxLi",
            "id": 8086184,
            "node_id": "MDQ6VXNlcjgwODYxODQ=",
            "avatar_url": "https://avatars.githubusercontent.com/u/8086184?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/pxLi",
            "html_url": "https://github.com/pxLi",
            "followers_url": "https://api.github.com/users/pxLi/followers",
            "following_url": "https://api.github.com/users/pxLi/following{/other_user}",
            "gists_url": "https://api.github.com/users/pxLi/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/pxLi/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/pxLi/subscriptions",
            "organizations_url": "https://api.github.com/users/pxLi/orgs",
            "repos_url": "https://api.github.com/users/pxLi/repos",
            "events_url": "https://api.github.com/users/pxLi/events{/privacy}",
            "received_events_url": "https://api.github.com/users/pxLi/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2023-11-01T05:23:01Z",
        "updated_at": "2023-11-01T05:24:12Z",
        "author_association": "COLLABORATOR",
        "body": "We only see this core dump in https://github.com/NVIDIA/spark-rapids/pull/9576 before the patch https://github.com/NVIDIA/spark-rapids/commit/9f12c272259e2c3c355e95ece980535f020bd93a and 100% repro in CI. (did not see any other place to report the same core dump)\r\n\r\nso previous commits in the change might actually help trigger the segfault",
        "reactions": {
            "url": "https://api.github.com/repos/NVIDIA/spark-rapids/issues/comments/1788428391/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    }
]