[
    {
        "url": "https://api.github.com/repos/rapidsai/cudf/issues/comments/2117878564",
        "html_url": "https://github.com/rapidsai/cudf/issues/11795#issuecomment-2117878564",
        "issue_url": "https://api.github.com/repos/rapidsai/cudf/issues/11795",
        "id": 2117878564,
        "node_id": "IC_kwDOBWUGps5-PEMk",
        "user": {
            "login": "vyasr",
            "id": 1538165,
            "node_id": "MDQ6VXNlcjE1MzgxNjU=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1538165?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/vyasr",
            "html_url": "https://github.com/vyasr",
            "followers_url": "https://api.github.com/users/vyasr/followers",
            "following_url": "https://api.github.com/users/vyasr/following{/other_user}",
            "gists_url": "https://api.github.com/users/vyasr/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/vyasr/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/vyasr/subscriptions",
            "organizations_url": "https://api.github.com/users/vyasr/orgs",
            "repos_url": "https://api.github.com/users/vyasr/repos",
            "events_url": "https://api.github.com/users/vyasr/events{/privacy}",
            "received_events_url": "https://api.github.com/users/vyasr/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2024-05-17T15:44:31Z",
        "updated_at": "2024-05-17T15:44:31Z",
        "author_association": "CONTRIBUTOR",
        "body": "This works now, but with the caveat that categorical column must be explicitly marked as ordered\r\n```\r\nIn [1]: import cudf\r\n   ...: import dask_cudf\r\n   ...: df = cudf.DataFrame({\"a\": list(\"caba\"), \"b\": list(range(4))})\r\n   ...: df[\"a\"] = df[\"a\"].astype(\"category\").cat.as_ordered()  # Without ordering the dask version fails.\r\n   ...: ddf = dask_cudf.from_cudf(df, npartitions=2)\r\n   ...: print(df.sort_values(\"a\"))\r\n   ...: print(ddf.sort_values(\"a\").compute())\r\n   a  b\r\n1  a  1\r\n3  a  3\r\n2  b  2\r\n0  c  0\r\n   a  b\r\n1  a  1\r\n3  a  3\r\n2  b  2\r\n0  c  0\r\n```\r\n@rjzamora any idea why dask_cudf behaves differently from cudf w.r.t. the ordering?",
        "reactions": {
            "url": "https://api.github.com/repos/rapidsai/cudf/issues/comments/2117878564/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/rapidsai/cudf/issues/comments/2118440759",
        "html_url": "https://github.com/rapidsai/cudf/issues/11795#issuecomment-2118440759",
        "issue_url": "https://api.github.com/repos/rapidsai/cudf/issues/11795",
        "id": 2118440759,
        "node_id": "IC_kwDOBWUGps5-RNc3",
        "user": {
            "login": "rjzamora",
            "id": 20461013,
            "node_id": "MDQ6VXNlcjIwNDYxMDEz",
            "avatar_url": "https://avatars.githubusercontent.com/u/20461013?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/rjzamora",
            "html_url": "https://github.com/rjzamora",
            "followers_url": "https://api.github.com/users/rjzamora/followers",
            "following_url": "https://api.github.com/users/rjzamora/following{/other_user}",
            "gists_url": "https://api.github.com/users/rjzamora/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/rjzamora/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/rjzamora/subscriptions",
            "organizations_url": "https://api.github.com/users/rjzamora/orgs",
            "repos_url": "https://api.github.com/users/rjzamora/repos",
            "events_url": "https://api.github.com/users/rjzamora/events{/privacy}",
            "received_events_url": "https://api.github.com/users/rjzamora/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2024-05-17T22:13:27Z",
        "updated_at": "2024-05-17T22:16:32Z",
        "author_association": "MEMBER",
        "body": "Good catch @vyasr - The dask behavior was actually \"fixed\" recently in dask-expr (https://github.com/dask/dask-expr/pull/1058), but I just realized that the `pd.CategoricalDtype` check will need to be updated to work for cudf (my mistake for missing that when I reviewed).\r\n\r\nEven with dask-expr fixed, however, your snippet will not work for dask_cudf, because there seems to be a bug in cudf:\r\n\r\n```python\r\nimport cudf as lib  # Works for pandas, but not for cudf\r\n\r\ndf = lib.DataFrame({\"a\": list(\"caba\"), \"b\": list(range(4))})\r\ndf[\"a\"] = df[\"a\"].astype(\"category\")\r\ndf = df.iloc[:2]\r\ndf[\"a\"].cat.as_ordered()\r\n```\r\n```\r\n...\r\nValueError: Length of values (4) does not match length of index (2)\r\n```\r\n\r\n**EDIT**: I submitted https://github.com/rapidsai/cudf/issues/15778 to track this.",
        "reactions": {
            "url": "https://api.github.com/repos/rapidsai/cudf/issues/comments/2118440759/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/rapidsai/cudf/issues/comments/2121052488",
        "html_url": "https://github.com/rapidsai/cudf/issues/11795#issuecomment-2121052488",
        "issue_url": "https://api.github.com/repos/rapidsai/cudf/issues/11795",
        "id": 2121052488,
        "node_id": "IC_kwDOBWUGps5-bLFI",
        "user": {
            "login": "rjzamora",
            "id": 20461013,
            "node_id": "MDQ6VXNlcjIwNDYxMDEz",
            "avatar_url": "https://avatars.githubusercontent.com/u/20461013?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/rjzamora",
            "html_url": "https://github.com/rjzamora",
            "followers_url": "https://api.github.com/users/rjzamora/followers",
            "following_url": "https://api.github.com/users/rjzamora/following{/other_user}",
            "gists_url": "https://api.github.com/users/rjzamora/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/rjzamora/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/rjzamora/subscriptions",
            "organizations_url": "https://api.github.com/users/rjzamora/orgs",
            "repos_url": "https://api.github.com/users/rjzamora/repos",
            "events_url": "https://api.github.com/users/rjzamora/events{/privacy}",
            "received_events_url": "https://api.github.com/users/rjzamora/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2024-05-20T19:17:44Z",
        "updated_at": "2024-05-20T19:17:44Z",
        "author_association": "MEMBER",
        "body": "**Update**: Latest version of `dask-expr:main` + `dask:main` now results in an ugly segfault when sorting on a categorical column. After https://github.com/rapidsai/cudf/pull/15788, the user will get a clear error until the upstream divisions logic is \"generalized\" to work with cudf.",
        "reactions": {
            "url": "https://api.github.com/repos/rapidsai/cudf/issues/comments/2121052488/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/rapidsai/cudf/issues/comments/2121229790",
        "html_url": "https://github.com/rapidsai/cudf/issues/11795#issuecomment-2121229790",
        "issue_url": "https://api.github.com/repos/rapidsai/cudf/issues/11795",
        "id": 2121229790,
        "node_id": "IC_kwDOBWUGps5-b2Xe",
        "user": {
            "login": "vyasr",
            "id": 1538165,
            "node_id": "MDQ6VXNlcjE1MzgxNjU=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1538165?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/vyasr",
            "html_url": "https://github.com/vyasr",
            "followers_url": "https://api.github.com/users/vyasr/followers",
            "following_url": "https://api.github.com/users/vyasr/following{/other_user}",
            "gists_url": "https://api.github.com/users/vyasr/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/vyasr/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/vyasr/subscriptions",
            "organizations_url": "https://api.github.com/users/vyasr/orgs",
            "repos_url": "https://api.github.com/users/vyasr/repos",
            "events_url": "https://api.github.com/users/vyasr/events{/privacy}",
            "received_events_url": "https://api.github.com/users/vyasr/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2024-05-20T21:19:34Z",
        "updated_at": "2024-05-20T21:19:34Z",
        "author_association": "CONTRIBUTOR",
        "body": "The chain has gotten a bit long here, let me summarize to make sure I have everything right. #15780 will fix #15778. Once that is merged, will this issue also be fixed in the dask-expr case, or is there still work to be done to generalize dask-expr to work correctly for cudf because https://github.com/dask/dask-expr/pull/1058 wasn't complete? And in either case, do we still expect this to fail for users of the legacy dask API (which I guess isn't too important if we're going to be forced to migrate to dask-expr anyway)?",
        "reactions": {
            "url": "https://api.github.com/repos/rapidsai/cudf/issues/comments/2121229790/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/rapidsai/cudf/issues/comments/2121418291",
        "html_url": "https://github.com/rapidsai/cudf/issues/11795#issuecomment-2121418291",
        "issue_url": "https://api.github.com/repos/rapidsai/cudf/issues/11795",
        "id": 2121418291,
        "node_id": "IC_kwDOBWUGps5-ckYz",
        "user": {
            "login": "rjzamora",
            "id": 20461013,
            "node_id": "MDQ6VXNlcjIwNDYxMDEz",
            "avatar_url": "https://avatars.githubusercontent.com/u/20461013?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/rjzamora",
            "html_url": "https://github.com/rjzamora",
            "followers_url": "https://api.github.com/users/rjzamora/followers",
            "following_url": "https://api.github.com/users/rjzamora/following{/other_user}",
            "gists_url": "https://api.github.com/users/rjzamora/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/rjzamora/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/rjzamora/subscriptions",
            "organizations_url": "https://api.github.com/users/rjzamora/orgs",
            "repos_url": "https://api.github.com/users/rjzamora/repos",
            "events_url": "https://api.github.com/users/rjzamora/events{/privacy}",
            "received_events_url": "https://api.github.com/users/rjzamora/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2024-05-20T23:42:12Z",
        "updated_at": "2024-05-20T23:44:13Z",
        "author_association": "MEMBER",
        "body": "**Summary**:\r\n\r\n- Sorting by a categorical column works fine with dask-cudf, but only for the \"legacy\" API\r\n- Until recently, categorical sorting has been broken for **both** pandas and cudf-backed data in dask-expr\r\n  - https://github.com/dask/dask-expr/pull/1058 fixed the problem for pandas-backed data, but not for cudf-backed data\r\n  \r\n- In order to support cudf-backed data, we essentially need the [`RepartitionQuantiles`](https://github.com/dask/dask-expr/blob/8de39b0c9ccf61411a71bf2f91d4f38397d4c004/dask_expr/_quantiles.py#L36) logic to work for both cudf and pandas data\r\n  - https://github.com/rapidsai/cudf/pull/15780 will indeed fix one of the reasons this logic doesn't work with cudf (a cudf slicing bug)\r\n  - https://github.com/dask/dask-expr/pull/1070 fixed another problem in `RepartitionQuantiles`, but it didn't fix everything\r\n    - The fact that this PR was only a \"partial\" fix ultimately motivated https://github.com/rapidsai/cudf/pull/15788, because the new failure mode was even worse than before.\r\n    \r\nI certainly want to fix categorical sorting for 24.06 if possible, but my current expectation is that we will need to raise an error and tell the user to disable query planning. If I can find a work-around in the next day or so, then we can remove the error. Otherwise, the proper/upstream fix will only apply to 24.08.",
        "reactions": {
            "url": "https://api.github.com/repos/rapidsai/cudf/issues/comments/2121418291/reactions",
            "total_count": 1,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 1,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    }
]