[
    {
        "url": "https://api.github.com/repos/rapidsai/cudf/issues/comments/994931576",
        "html_url": "https://github.com/rapidsai/cudf/issues/9676#issuecomment-994931576",
        "issue_url": "https://api.github.com/repos/rapidsai/cudf/issues/9676",
        "id": 994931576,
        "node_id": "IC_kwDOBWUGps47TXN4",
        "user": {
            "login": "github-actions[bot]",
            "id": 41898282,
            "node_id": "MDM6Qm90NDE4OTgyODI=",
            "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/github-actions%5Bbot%5D",
            "html_url": "https://github.com/apps/github-actions",
            "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
            "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
            "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
            "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
            "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
            "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
            "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
            "type": "Bot",
            "site_admin": false
        },
        "created_at": "2021-12-15T16:02:49Z",
        "updated_at": "2021-12-15T16:02:49Z",
        "author_association": "NONE",
        "body": "This issue has been labeled `inactive-30d` due to no recent activity in the past 30 days. Please close this issue if no further response or action is needed. Otherwise, please respond with a comment indicating any updates or changes to the original issue and/or confirm this issue still needs to be addressed. This issue will be labeled `inactive-90d` if there is no activity in the next 60 days.",
        "reactions": {
            "url": "https://api.github.com/repos/rapidsai/cudf/issues/comments/994931576/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/rapidsai/cudf/issues/comments/1068168563",
        "html_url": "https://github.com/rapidsai/cudf/issues/9676#issuecomment-1068168563",
        "issue_url": "https://api.github.com/repos/rapidsai/cudf/issues/9676",
        "id": 1068168563,
        "node_id": "IC_kwDOBWUGps4_qvVz",
        "user": {
            "login": "github-actions[bot]",
            "id": 41898282,
            "node_id": "MDM6Qm90NDE4OTgyODI=",
            "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/github-actions%5Bbot%5D",
            "html_url": "https://github.com/apps/github-actions",
            "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
            "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
            "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
            "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
            "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
            "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
            "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
            "type": "Bot",
            "site_admin": false
        },
        "created_at": "2022-03-15T16:07:48Z",
        "updated_at": "2022-03-15T16:07:48Z",
        "author_association": "NONE",
        "body": "This issue has been labeled `inactive-90d` due to no recent activity in the past 90 days. Please close this issue if no further response or action is needed. Otherwise, please respond with a comment indicating any updates or changes to the original issue and/or confirm this issue still needs to be addressed.",
        "reactions": {
            "url": "https://api.github.com/repos/rapidsai/cudf/issues/comments/1068168563/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/rapidsai/cudf/issues/comments/1217003322",
        "html_url": "https://github.com/rapidsai/cudf/issues/9676#issuecomment-1217003322",
        "issue_url": "https://api.github.com/repos/rapidsai/cudf/issues/9676",
        "id": 1217003322,
        "node_id": "IC_kwDOBWUGps5Iif86",
        "user": {
            "login": "galipremsagar",
            "id": 11664259,
            "node_id": "MDQ6VXNlcjExNjY0MjU5",
            "avatar_url": "https://avatars.githubusercontent.com/u/11664259?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/galipremsagar",
            "html_url": "https://github.com/galipremsagar",
            "followers_url": "https://api.github.com/users/galipremsagar/followers",
            "following_url": "https://api.github.com/users/galipremsagar/following{/other_user}",
            "gists_url": "https://api.github.com/users/galipremsagar/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/galipremsagar/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/galipremsagar/subscriptions",
            "organizations_url": "https://api.github.com/users/galipremsagar/orgs",
            "repos_url": "https://api.github.com/users/galipremsagar/repos",
            "events_url": "https://api.github.com/users/galipremsagar/events{/privacy}",
            "received_events_url": "https://api.github.com/users/galipremsagar/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2022-08-16T18:33:26Z",
        "updated_at": "2022-08-16T18:33:26Z",
        "author_association": "CONTRIBUTOR",
        "body": "With the recent changes to csv reader, the current behavior seems to be that we are returning an empty dataframe. To me, it seems like an _okay_ behavior?:\r\n\r\n```python\r\nIn [4]: import pandas as pd\r\n   ...: \r\n   ...: with open('test.csv', 'w') as fp:\r\n   ...:     fp.write('')\r\n   ...: \r\n\r\nIn [5]: cudf.read_csv(\"test.csv\")\r\nOut[5]: \r\nEmpty DataFrame\r\nColumns: []\r\nIndex: []\r\n```\r\n\r\n@randerzander is this an agreeable behavior in this scenario? or do you think otherwise?",
        "reactions": {
            "url": "https://api.github.com/repos/rapidsai/cudf/issues/comments/1217003322/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/rapidsai/cudf/issues/comments/2108985613",
        "html_url": "https://github.com/rapidsai/cudf/issues/9676#issuecomment-2108985613",
        "issue_url": "https://api.github.com/repos/rapidsai/cudf/issues/9676",
        "id": 2108985613,
        "node_id": "IC_kwDOBWUGps59tJEN",
        "user": {
            "login": "vyasr",
            "id": 1538165,
            "node_id": "MDQ6VXNlcjE1MzgxNjU=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1538165?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/vyasr",
            "html_url": "https://github.com/vyasr",
            "followers_url": "https://api.github.com/users/vyasr/followers",
            "following_url": "https://api.github.com/users/vyasr/following{/other_user}",
            "gists_url": "https://api.github.com/users/vyasr/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/vyasr/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/vyasr/subscriptions",
            "organizations_url": "https://api.github.com/users/vyasr/orgs",
            "repos_url": "https://api.github.com/users/vyasr/repos",
            "events_url": "https://api.github.com/users/vyasr/events{/privacy}",
            "received_events_url": "https://api.github.com/users/vyasr/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2024-05-13T23:23:50Z",
        "updated_at": "2024-05-13T23:23:50Z",
        "author_association": "CONTRIBUTOR",
        "body": "The above is still the status quo here:\r\n```\r\n>>> import pandas as pd\r\n>>> import cudf\r\n>>> with open(\"test.csv\", \"w\") as fp:\r\n...     fp.write(\"\")\r\n... \r\n0\r\n>>> pd.read_csv(\"test.csv\")\r\nTraceback (most recent call last):\r\n  File \"<stdin>\", line 1, in <module>\r\n  File \"/home/coder/.conda/envs/rapids/lib/python3.10/site-packages/pandas/io/parsers/readers.py\", line 1026, in read_csv\r\n    return _read(filepath_or_buffer, kwds)\r\n  File \"/home/coder/.conda/envs/rapids/lib/python3.10/site-packages/pandas/io/parsers/readers.py\", line 620, in _read\r\n    parser = TextFileReader(filepath_or_buffer, **kwds)\r\n  File \"/home/coder/.conda/envs/rapids/lib/python3.10/site-packages/pandas/io/parsers/readers.py\", line 1620, in __init__\r\n    self._engine = self._make_engine(f, self.engine)\r\n  File \"/home/coder/.conda/envs/rapids/lib/python3.10/site-packages/pandas/io/parsers/readers.py\", line 1898, in _make_engine\r\n    return mapping[engine](f, **self.options)\r\n  File \"/home/coder/.conda/envs/rapids/lib/python3.10/site-packages/pandas/io/parsers/c_parser_wrapper.py\", line 93, in __init__\r\n    self._reader = parsers.TextReader(src, **kwds)\r\n  File \"parsers.pyx\", line 581, in pandas._libs.parsers.TextReader.__cinit__\r\npandas.errors.EmptyDataError: No columns to parse from file\r\n>>> cudf.read_csv(\"test.csv\")\r\nEmpty DataFrame\r\nColumns: []\r\nIndex: []\r\n```\r\n\r\nGiven the growth of cudf.pandas since this issue was first created, we probably want to aim for closer matching now.",
        "reactions": {
            "url": "https://api.github.com/repos/rapidsai/cudf/issues/comments/2108985613/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    }
]