[
    {
        "url": "https://api.github.com/repos/rapidsai/cudf/issues/comments/1474124965",
        "html_url": "https://github.com/rapidsai/cudf/issues/12501#issuecomment-1474124965",
        "issue_url": "https://api.github.com/repos/rapidsai/cudf/issues/12501",
        "id": 1474124965,
        "node_id": "IC_kwDOBWUGps5X3Vyl",
        "user": {
            "login": "GregoryKimball",
            "id": 12725111,
            "node_id": "MDQ6VXNlcjEyNzI1MTEx",
            "avatar_url": "https://avatars.githubusercontent.com/u/12725111?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/GregoryKimball",
            "html_url": "https://github.com/GregoryKimball",
            "followers_url": "https://api.github.com/users/GregoryKimball/followers",
            "following_url": "https://api.github.com/users/GregoryKimball/following{/other_user}",
            "gists_url": "https://api.github.com/users/GregoryKimball/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/GregoryKimball/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/GregoryKimball/subscriptions",
            "organizations_url": "https://api.github.com/users/GregoryKimball/orgs",
            "repos_url": "https://api.github.com/users/GregoryKimball/repos",
            "events_url": "https://api.github.com/users/GregoryKimball/events{/privacy}",
            "received_events_url": "https://api.github.com/users/GregoryKimball/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2023-03-17T16:53:16Z",
        "updated_at": "2023-03-17T16:53:16Z",
        "author_association": "CONTRIBUTOR",
        "body": "Thank you @lvxhnat for sharing these results. Would you please post a code snippet that reproduces the issue?",
        "reactions": {
            "url": "https://api.github.com/repos/rapidsai/cudf/issues/comments/1474124965/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/rapidsai/cudf/issues/comments/1484456076",
        "html_url": "https://github.com/rapidsai/cudf/issues/12501#issuecomment-1484456076",
        "issue_url": "https://api.github.com/repos/rapidsai/cudf/issues/12501",
        "id": 1484456076,
        "node_id": "IC_kwDOBWUGps5YewCM",
        "user": {
            "login": "lvxhnat",
            "id": 58301316,
            "node_id": "MDQ6VXNlcjU4MzAxMzE2",
            "avatar_url": "https://avatars.githubusercontent.com/u/58301316?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/lvxhnat",
            "html_url": "https://github.com/lvxhnat",
            "followers_url": "https://api.github.com/users/lvxhnat/followers",
            "following_url": "https://api.github.com/users/lvxhnat/following{/other_user}",
            "gists_url": "https://api.github.com/users/lvxhnat/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/lvxhnat/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/lvxhnat/subscriptions",
            "organizations_url": "https://api.github.com/users/lvxhnat/orgs",
            "repos_url": "https://api.github.com/users/lvxhnat/repos",
            "events_url": "https://api.github.com/users/lvxhnat/events{/privacy}",
            "received_events_url": "https://api.github.com/users/lvxhnat/received_events",
            "type": "User",
            "site_admin": false
        },
        "created_at": "2023-03-27T04:03:48Z",
        "updated_at": "2023-03-27T04:03:48Z",
        "author_association": "NONE",
        "body": "@GregoryKimball  Hi Gregory, apologies for the late reply. This issue seems to be general and not specific to my dataset. This is what I did to replicate: \r\n\r\nIn file ```df_memory_test.py```\r\n```python\r\nimport cudf\r\nimport numpy as np\r\nimport pandas as pd\r\nfrom memory_profiler import profile\r\n\r\n@profile\r\ndef df_memory_test():\r\n    rands = [np.random.random(1000) for i in range(3)]\r\n    pd_df: pd.DataFrame = pd.DataFrame(rands).T\r\n    pd_df.columns = ['sample_a', 'sample_b', 'sample_c']\r\n    cu_df: cudf.DataFrame = cudf.DataFrame(pd_df)\r\n    return \r\n\r\nif __name__ ==  '__main__':\r\n   df_memory_test()\r\n```\r\n\r\nthen ```python -m memory_profiler df_memory_test.py```\r\n\r\nshows a memory spike during the conversion similarly:\r\n\r\n```\r\nLine #    Mem usage    Increment  Occurrences   Line Contents\r\n=============================================================\r\n     6    596.6 MiB    596.6 MiB           1   @profile\r\n     7                                         def df_memory_test():\r\n     8    596.6 MiB      0.0 MiB           6       rands = [np.random.random(1000) for i in range(3)]\r\n     9    597.4 MiB      0.8 MiB           1       pd_df: pd.DataFrame = pd.DataFrame(rands).T\r\n    10    597.4 MiB      0.0 MiB           1       pd_df.columns = ['sample_a', 'sample_b', 'sample_c']\r\n    11   2436.6 MiB   1839.2 MiB           1       cu_df: cudf.DataFrame = cudf.DataFrame(pd_df)\r\n    12   2436.6 MiB      0.0 MiB           1       return \r\n```",
        "reactions": {
            "url": "https://api.github.com/repos/rapidsai/cudf/issues/comments/1484456076/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "performed_via_github_app": null
    }
]