{
    "url": "https://api.github.com/repos/rapidsai/cudf/issues/14627",
    "repository_url": "https://api.github.com/repos/rapidsai/cudf",
    "labels_url": "https://api.github.com/repos/rapidsai/cudf/issues/14627/labels{/name}",
    "comments_url": "https://api.github.com/repos/rapidsai/cudf/issues/14627/comments",
    "events_url": "https://api.github.com/repos/rapidsai/cudf/issues/14627/events",
    "html_url": "https://github.com/rapidsai/cudf/issues/14627",
    "id": 2041509329,
    "node_id": "I_kwDOBWUGps55rvXR",
    "number": 14627,
    "title": "[BUG] `as_column` of pandas timestamps delivers different resolution datetime depending on whether we pass a scalar or list",
    "user": {
        "login": "wence-",
        "id": 1126981,
        "node_id": "MDQ6VXNlcjExMjY5ODE=",
        "avatar_url": "https://avatars.githubusercontent.com/u/1126981?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/wence-",
        "html_url": "https://github.com/wence-",
        "followers_url": "https://api.github.com/users/wence-/followers",
        "following_url": "https://api.github.com/users/wence-/following{/other_user}",
        "gists_url": "https://api.github.com/users/wence-/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/wence-/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/wence-/subscriptions",
        "organizations_url": "https://api.github.com/users/wence-/orgs",
        "repos_url": "https://api.github.com/users/wence-/repos",
        "events_url": "https://api.github.com/users/wence-/events{/privacy}",
        "received_events_url": "https://api.github.com/users/wence-/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [
        {
            "id": 599626559,
            "node_id": "MDU6TGFiZWw1OTk2MjY1NTk=",
            "url": "https://api.github.com/repos/rapidsai/cudf/labels/bug",
            "name": "bug",
            "color": "d73a4a",
            "default": true,
            "description": "Something isn't working"
        }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 3,
    "created_at": "2023-12-14T11:33:07Z",
    "updated_at": "2024-03-04T15:41:48Z",
    "closed_at": null,
    "author_association": "CONTRIBUTOR",
    "active_lock_reason": null,
    "body": "**Describe the bug**\r\n\r\n```\r\nimport pandas as pd\r\nfrom cudf.core.column import as_column\r\n\r\ndata = pd.Timestamp(\"2000-01-01\")\r\n\r\nfrom_scalar = as_column(data)\r\nfrom_list = as_column([data])\r\n\r\nassert from_scalar.dtype == from_list.dtype # False\r\n```\r\n\r\n**Expected behavior**\r\n\r\nThe resolution should be inferred consistently. Note that `cudf.Scalar(data)` infers the same (nanosecond) resolution as `as_column([data])`.",
    "closed_by": null,
    "reactions": {
        "url": "https://api.github.com/repos/rapidsai/cudf/issues/14627/reactions",
        "total_count": 0,
        "+1": 0,
        "-1": 0,
        "laugh": 0,
        "hooray": 0,
        "confused": 0,
        "heart": 0,
        "rocket": 0,
        "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/rapidsai/cudf/issues/14627/timeline",
    "performed_via_github_app": null,
    "state_reason": null
}