{
    "url": "https://api.github.com/repos/rapidsai/cudf/issues/11606",
    "repository_url": "https://api.github.com/repos/rapidsai/cudf",
    "labels_url": "https://api.github.com/repos/rapidsai/cudf/issues/11606/labels{/name}",
    "comments_url": "https://api.github.com/repos/rapidsai/cudf/issues/11606/comments",
    "events_url": "https://api.github.com/repos/rapidsai/cudf/issues/11606/events",
    "html_url": "https://github.com/rapidsai/cudf/issues/11606",
    "id": 1351455945,
    "node_id": "I_kwDOBWUGps5QjZTJ",
    "number": 11606,
    "title": "[BUG] Series accessors aren't being doctested.",
    "user": {
        "login": "bdice",
        "id": 3943761,
        "node_id": "MDQ6VXNlcjM5NDM3NjE=",
        "avatar_url": "https://avatars.githubusercontent.com/u/3943761?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/bdice",
        "html_url": "https://github.com/bdice",
        "followers_url": "https://api.github.com/users/bdice/followers",
        "following_url": "https://api.github.com/users/bdice/following{/other_user}",
        "gists_url": "https://api.github.com/users/bdice/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/bdice/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/bdice/subscriptions",
        "organizations_url": "https://api.github.com/users/bdice/orgs",
        "repos_url": "https://api.github.com/users/bdice/repos",
        "events_url": "https://api.github.com/users/bdice/events{/privacy}",
        "received_events_url": "https://api.github.com/users/bdice/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [
        {
            "id": 599626559,
            "node_id": "MDU6TGFiZWw1OTk2MjY1NTk=",
            "url": "https://api.github.com/repos/rapidsai/cudf/labels/bug",
            "name": "bug",
            "color": "d73a4a",
            "default": true,
            "description": "Something isn't working"
        },
        {
            "id": 1139741213,
            "node_id": "MDU6TGFiZWwxMTM5NzQxMjEz",
            "url": "https://api.github.com/repos/rapidsai/cudf/labels/Python",
            "name": "Python",
            "color": "1d76db",
            "default": false,
            "description": "Affects Python cuDF API."
        }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 1,
    "created_at": "2022-08-25T21:12:24Z",
    "updated_at": "2023-04-02T22:40:37Z",
    "closed_at": null,
    "author_association": "CONTRIBUTOR",
    "active_lock_reason": null,
    "body": "**Describe the bug**\r\nIt appears that the special type accessors for `Series.str` (`StringMethods`) are not being doctested. See https://github.com/rapidsai/cudf/pull/11575#discussion_r953925683. I suspect this is also true for list and struct accessors but have not verified that.\r\n\r\n**Expected behavior**\r\nDoctests should run for type-accessors inheriting from `ColumnMethods` like `Series.str.findall`.\r\n\r\nThis will probably require some updates to [test_doctests.py](https://github.com/rapidsai/cudf/blob/main/python/cudf/cudf/tests/test_doctests.py) to ensure that these accessor methods are found and tested. It may require a special set of tests explicitly designed for finding and testing all `ColumnMethods` objects.",
    "closed_by": null,
    "reactions": {
        "url": "https://api.github.com/repos/rapidsai/cudf/issues/11606/reactions",
        "total_count": 0,
        "+1": 0,
        "-1": 0,
        "laugh": 0,
        "hooray": 0,
        "confused": 0,
        "heart": 0,
        "rocket": 0,
        "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/rapidsai/cudf/issues/11606/timeline",
    "performed_via_github_app": null,
    "state_reason": null
}