{
    "url": "https://api.github.com/repos/rapidsai/cudf/issues/15694",
    "repository_url": "https://api.github.com/repos/rapidsai/cudf",
    "labels_url": "https://api.github.com/repos/rapidsai/cudf/issues/15694/labels{/name}",
    "comments_url": "https://api.github.com/repos/rapidsai/cudf/issues/15694/comments",
    "events_url": "https://api.github.com/repos/rapidsai/cudf/issues/15694/events",
    "html_url": "https://github.com/rapidsai/cudf/issues/15694",
    "id": 2284115894,
    "node_id": "I_kwDOBWUGps6IJNe2",
    "number": 15694,
    "title": "[BUG] cudf.pandas wrapped numpy arrays not compatible with numba",
    "user": {
        "login": "AjayThorve",
        "id": 20476096,
        "node_id": "MDQ6VXNlcjIwNDc2MDk2",
        "avatar_url": "https://avatars.githubusercontent.com/u/20476096?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/AjayThorve",
        "html_url": "https://github.com/AjayThorve",
        "followers_url": "https://api.github.com/users/AjayThorve/followers",
        "following_url": "https://api.github.com/users/AjayThorve/following{/other_user}",
        "gists_url": "https://api.github.com/users/AjayThorve/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/AjayThorve/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/AjayThorve/subscriptions",
        "organizations_url": "https://api.github.com/users/AjayThorve/orgs",
        "repos_url": "https://api.github.com/users/AjayThorve/repos",
        "events_url": "https://api.github.com/users/AjayThorve/events{/privacy}",
        "received_events_url": "https://api.github.com/users/AjayThorve/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [
        {
            "id": 599626559,
            "node_id": "MDU6TGFiZWw1OTk2MjY1NTk=",
            "url": "https://api.github.com/repos/rapidsai/cudf/labels/bug",
            "name": "bug",
            "color": "d73a4a",
            "default": true,
            "description": "Something isn't working"
        },
        {
            "id": 6815620706,
            "node_id": "LA_kwDOBWUGps8AAAABlj4eYg",
            "url": "https://api.github.com/repos/rapidsai/cudf/labels/cudf.pandas",
            "name": "cudf.pandas",
            "color": "984DFB",
            "default": false,
            "description": "Issues specific to cudf.pandas"
        }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": {
        "url": "https://api.github.com/repos/rapidsai/cudf/milestones/35",
        "html_url": "https://github.com/rapidsai/cudf/milestone/35",
        "labels_url": "https://api.github.com/repos/rapidsai/cudf/milestones/35/labels",
        "id": 10812591,
        "node_id": "MI_kwDOBWUGps4ApPyv",
        "number": 35,
        "title": "Proxying - cudf.pandas",
        "description": "",
        "creator": {
            "login": "galipremsagar",
            "id": 11664259,
            "node_id": "MDQ6VXNlcjExNjY0MjU5",
            "avatar_url": "https://avatars.githubusercontent.com/u/11664259?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/galipremsagar",
            "html_url": "https://github.com/galipremsagar",
            "followers_url": "https://api.github.com/users/galipremsagar/followers",
            "following_url": "https://api.github.com/users/galipremsagar/following{/other_user}",
            "gists_url": "https://api.github.com/users/galipremsagar/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/galipremsagar/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/galipremsagar/subscriptions",
            "organizations_url": "https://api.github.com/users/galipremsagar/orgs",
            "repos_url": "https://api.github.com/users/galipremsagar/repos",
            "events_url": "https://api.github.com/users/galipremsagar/events{/privacy}",
            "received_events_url": "https://api.github.com/users/galipremsagar/received_events",
            "type": "User",
            "site_admin": false
        },
        "open_issues": 16,
        "closed_issues": 13,
        "state": "open",
        "created_at": "2024-04-12T16:41:23Z",
        "updated_at": "2024-06-03T21:47:19Z",
        "due_on": null,
        "closed_at": null
    },
    "comments": 4,
    "created_at": "2024-05-07T19:56:09Z",
    "updated_at": "2024-05-23T14:46:55Z",
    "closed_at": null,
    "author_association": "MEMBER",
    "active_lock_reason": null,
    "body": "**Describe the bug**\r\nWhen I try to use cudf.pandas with [datashader](https://github.com/holoviz/datashader), I get an error `Cannot determine Numba type of <class 'cudf.pandas._wrappers.numpy.ndarray'>`, full repro below. Datashader actually works directly with cudf, and a cudf.DataFrame is an exceptable data format. But using cudf as a no-code-change accelerator for pandas, this seems to fail.\r\n\r\n\r\n**Steps/Code to reproduce bug**\r\n\r\n```python\r\nimport cudf.pandas\r\ncudf.pandas.install()\r\n\r\nimport pandas as pd\r\nimport numpy as np\r\nimport datashader as ds\r\nimport datashader.transfer_functions as tf\r\nfrom datashader.colors import inferno\r\n\r\n# Create a small dataset\r\nnp.random.seed(0)\r\nn = 1000\r\ndf = pd.DataFrame({\r\n    'x': np.random.normal(0, 1, n),\r\n    'y': np.random.normal(0, 1, n)\r\n})\r\n\r\n# Create a canvas to render the plot\r\ncvs = ds.Canvas(plot_width=400, plot_height=400)\r\n\r\n# Aggregate the points in the canvas\r\nagg = cvs.points(df, 'x', 'y')\r\n\r\n# Render the plot using a transfer function\r\nimg = tf.shade(agg, cmap=inferno, how='eq_hist')\r\n\r\n# Display the plot\r\nimg\r\n```\r\nOutput\r\n```bash\r\nTypingError: Failed in nopython mode pipeline (step: nopython frontend)\r\nnon-precise type pyobject\r\nDuring: typing of argument at [/home/ajay/miniconda3/envs/rapids-24.06/lib/python3.11/site-packages/datashader/glyphs/glyph.py](http://localhost:8888/lab/tree/dev/miniconda3/envs/rapids-24.06/lib/python3.11/site-packages/datashader/glyphs/glyph.py) (66)\r\n\r\nFile \".[./miniconda3/envs/rapids-24.06/lib/python3.11/site-packages/datashader/glyphs/glyph.py\", line 66](http://localhost:8888/lab/tree/dev/miniconda3/envs/rapids-24.06/lib/python3.11/site-packages/datashader/glyphs/glyph.py#line=65):\r\n    def _compute_bounds(s):\r\n        <source elided>\r\n\r\n    @staticmethod\r\n    ^ \r\n\r\nThis error may have been caused by the following argument(s):\r\n- argument 0: Cannot determine Numba type of <class 'cudf.pandas._wrappers.numpy.ndarray'>\r\n```\r\n\r\n**Expected behavior**\r\nIdeally same output as a cudf or a pandas dataframe.\r\n\r\n**Environment overview (please complete the following information)**\r\n - Environment location: Ubuntu\r\n - Method of cuDF install: Conda\r\n",
    "closed_by": null,
    "reactions": {
        "url": "https://api.github.com/repos/rapidsai/cudf/issues/15694/reactions",
        "total_count": 0,
        "+1": 0,
        "-1": 0,
        "laugh": 0,
        "hooray": 0,
        "confused": 0,
        "heart": 0,
        "rocket": 0,
        "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/rapidsai/cudf/issues/15694/timeline",
    "performed_via_github_app": null,
    "state_reason": null
}